---
name: DevSecOps Pipeline
on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'version'

  pull_request:
    types: [opened, synchronize, reopened]

env:
  # image repo name
  REPO_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_REPO_NAME }}

jobs:
  run-linters:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: get new version
        id: version
        run: |
          current_version="$(cat version)"
          new_version="$(echo "$current_version" | awk -F. '{$3 = $3 + 1;} 1' OFS=".")"
          echo "$new_version" > version
          echo "VERSION=$new_version" >> "$GITHUB_OUTPUT"

    outputs:
      VERSION: ${{ steps.version.outputs.VERSION }}

  sonarqube-analysis:
    needs: [run-linters]
    name: Sonarqube Analyze
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      
      - run: chmod +x mvnw 
     
      - name: Run Tests
        run: |
          ./mvnw clean test

      - name: Run tests and generate code coverage report
        run: ./mvnw verify

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: target/site/jacoco/index.html

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JaCoCo Report to S3  
        run: |
          mv target/site/jacoco/index.html target/site/jacoco/${{ needs.run-linters.outputs.VERSION }}.html
          aws s3 cp target/site/jacoco/${{ needs.run-linters.outputs.VERSION }}.html s3://devsecops-project-01/jacoco-reports/  

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://${{ secrets.SONAR_URL }}:8200/
          token: ${{ secrets.VAULT_TOKEN }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLEID }}
          secretId: ${{ secrets.VAULT_SECRETID}}
          secrets: |
            secrets/creds/sonar sonar-token | SONAR_TOKEN;
            secrets/creds/sonar sonar-project-key | SONAR_PROJECT_KEY;
          
      - name: SonarQube Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ steps.import-secrets.outputs.SONAR_TOKEN }}
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ steps.import-secrets.outputs.SONAR_PROJECT_KEY }}

  snyk-test:
    needs: [run-linters]
    name: Snyk Test
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: chmod +x mvnw
      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
   
  docker-build:
    needs: [run-linters, sonarqube-analysis]
    name: Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
            
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Maven Install
        run: |
          chmod +x mvnw  
          ./mvnw clean install 
          echo ${{ needs.run-linters.outputs.VERSION }} > version

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REPO_NAME }}:${{ needs.run-linters.outputs.VERSION }}
            ${{ env.REPO_NAME }}:latest
          cache-to: type=inline
      
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          add: version
          message: "version updated with tag ${{ needs.run-linters.outputs.VERSION }}"
          author_name: ${{ secrets.NAME }}
          author_email: ${{ secrets.EMAIL }}
  
  Trivy :
    needs: [docker-build, run-linters]
    name: Trivy Vulnerability Scanner for Containers
    runs-on: ubuntu-latest
    steps:
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1  

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REPO_NAME }}:latest'
          format: 'table'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.html'

      - name: Upload Trivy Report to S3  
        run: |
          mv trivy-results.html trivy-results-${{ needs.run-linters.outputs.VERSION }}.html
          aws s3 cp trivy-results-${{ needs.run-linters.outputs.VERSION }}.html s3://devsecops-project-01/trivy/ 

      
